[package]
name = "nui-system-core"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Nexa System Host core: commands, permissions, desktop backends"

[dependencies]
arboard = "3.6"
nui-protocol = { path = "../../protocol", version = "0.1.0" }
semver = "1.0"
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
