packages:
  - "packages/*"
  - "examples/counter"
  - "examples/perry-counter"
  - "examples/todo"
  - "examples/solid-counter"
  - "examples/vue-counter"
  - "examples/react-counter"
  - "examples/svelte-counter"
  - "examples/layout-playground"
