// @generated by tools/protocol-codegen.mjs; DO NOT EDIT.
// Source: protocol/common.json, protocol/nui-host.json, protocol/system-host.json.

declare const handleRefBrand: unique symbol;

export const NodeType = {
  Root: 0,
  View: 1,
  Text: 2,
  Image: 3,
  Scroll: 4,
} as const;
export type NodeType = (typeof NodeType)[keyof typeof NodeType];

export const PropertyId = {
  Width: 1,
  Height: 2,
  MinWidth: 3,
  MinHeight: 4,
  Padding: 5,
  Gap: 6,
  FlexDirection: 7,
  AlignItems: 8,
  JustifyContent: 9,
  BackgroundColor: 10,
  BorderRadius: 11,
  Opacity: 12,
  FontSize: 13,
  FontWeight: 14,
  TextColor: 15,
  ScrollOffsetY: 16,
  FlexGrow: 17,
  Disabled: 18,
} as const;
export type PropertyId = (typeof PropertyId)[keyof typeof PropertyId];

export const EventId = {
  Click: 1,
  Change: 2,
  Submit: 3,
  Pointer: 4,
  Wheel: 5,
  Keyboard: 6,
  TextInput: 7,
  Composition: 8,
  Focus: 9,
  WindowLifecycle: 10,
} as const;
export type EventId = (typeof EventId)[keyof typeof EventId];

export namespace Common {
  export interface ProtocolVersion {
    readonly major: number;
    readonly minor: number;
    readonly patch: number;
  }

  export interface AbiVersion {
    readonly major: number;
    readonly minor: number;
  }

  export interface FeatureBits {
    readonly low: number;
    readonly high: number;
  }

  export interface FeatureSet {
    readonly required: FeatureBits;
    readonly optional: FeatureBits;
  }

  export interface ProtocolHello {
    readonly protocol: ProtocolVersion;
    readonly abi: AbiVersion;
    readonly clientRuntimeVersion: string;
    readonly clientTargetTriple: string;
    readonly transport: FeatureSet;
    readonly ui: FeatureSet;
    readonly system: FeatureSet;
  }

  export interface ProtocolAccepted {
    readonly protocol: ProtocolVersion;
    readonly abi: AbiVersion;
    readonly hostRuntimeVersion: string;
    readonly hostTargetTriple: string;
    readonly transport: FeatureBits;
    readonly ui: FeatureBits;
    readonly system: FeatureBits;
  }

  export type HandleRef = Readonly<{
    readonly slot: number;
    readonly generation: number;
  }> & { readonly [handleRefBrand]: true };

  export enum ErrorSeverity {
    ProtocolViolation = "ProtocolViolation",
    RecoverableOperation = "RecoverableOperation",
    FrameFailure = "FrameFailure",
    FatalRuntime = "FatalRuntime",
  }

  export type ErrorContext = Readonly<Record<string, string | number | boolean>>;

  export interface NexaError {
    readonly domain: "protocol" | "ui" | "system";
    readonly code: number;
    readonly name: string;
    readonly severity: ErrorSeverity;
    readonly operation: string;
    readonly retryable: boolean;
    readonly message: string;
    readonly runtimeVersion: string;
    readonly context?: ErrorContext;
    readonly platformCode?: string;
    readonly cause?: NexaError;
  }

  export type NexaResult<T> =
    | Readonly<{ readonly ok: true; readonly value: T }>
    | Readonly<{ readonly ok: false; readonly error: NexaError }>;

  export const schemaVersion = 1 as const;
  export const protocolVersion = {
    major: 1,
    minor: 0,
    patch: 0,
  } as const;
  export const abiVersion = { major: 0, minor: 5 } as const;
  export const handleValidation = {
    slotMinimum: 0,
    slotMaximum: 4294967295,
    generationMinimum: 1,
    generationMaximum: 4294967295,
  } as const;
  export const handleTokenPattern = /^h1\/[0-9a-f]{8}\/[0-9a-f]{8}$/;
  export const resultCodec = "nexa_result_json_v1" as const;

  export enum FeatureBit {
    HandleRef = 0,
    StructuredErrors = 1,
  }

  export enum HandleKind {
    Node = 1,
    Callback = 2,
    Task = 3,
    Subscription = 4,
    NativeResource = 5,
  }

  export enum CommandId {
    Handshake = 0,
  }

  export enum ErrorCode {
    ProtocolMismatch = 65537,
    UnsupportedFeature = 65538,
  }

  export interface CommandParams {
    readonly [CommandId.Handshake]: readonly [hello: ProtocolHello];
  }

  export interface CommandResults {
    readonly [CommandId.Handshake]: ProtocolAccepted;
  }
}

export namespace Ui {
  export interface CommitReceipt {
    readonly sequence: number;
    readonly dirtyFlags: number;
  }

  export enum SemanticRole {
    None = "None",
    Button = "Button",
    Text = "Text",
    Image = "Image",
    TextInput = "TextInput",
    Scroll = "Scroll",
    Header = "Header",
  }

  export enum SemanticAction {
    Invoke = "Invoke",
    Focus = "Focus",
    SetValue = "SetValue",
  }

  export type SemanticActions = readonly SemanticAction[];

  export interface Semantics {
    readonly role?: SemanticRole;
    readonly label?: string;
    readonly value?: string;
    readonly description?: string;
    readonly disabled?: boolean;
    readonly checked?: boolean;
    readonly actions?: SemanticActions;
  }

  export interface TextRange {
    readonly start: number;
    readonly end: number;
  }

  export interface TextSelection {
    readonly anchor: number;
    readonly focus: number;
  }

  export interface Rect {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
  }

  export interface TextInputState {
    readonly text: string;
    readonly surroundingText: TextRange;
    readonly selection: TextSelection;
    readonly composition?: TextRange;
    readonly compositionBounds: Rect;
    readonly revision: string;
  }

  export interface EventModifiers {
    readonly shift: boolean;
    readonly control: boolean;
    readonly alt: boolean;
    readonly meta: boolean;
    readonly capsLock: boolean;
    readonly numLock: boolean;
  }

  export enum PropagationPhase {
    Capture = "Capture",
    Target = "Target",
    Bubble = "Bubble",
    DefaultAction = "DefaultAction",
  }

  export interface PropagationState {
    readonly phase: PropagationPhase;
    readonly defaultPrevented: boolean;
    readonly propagationStopped: boolean;
    readonly immediatePropagationStopped: boolean;
  }

  export interface EventContext {
    readonly windowId: number;
    readonly target: Common.HandleRef | null;
    readonly timestamp: string;
    readonly modifiers: EventModifiers;
    readonly propagation: PropagationState;
  }

  export enum PointerKind {
    Down = "Down",
    Move = "Move",
    Up = "Up",
    Cancel = "Cancel",
    Enter = "Enter",
    Leave = "Leave",
  }

  export enum KeyboardKind {
    Down = "Down",
    Up = "Up",
  }

  export enum CompositionKind {
    Start = "Start",
    Update = "Update",
    Commit = "Commit",
    Cancel = "Cancel",
  }

  export enum FocusKind {
    Gained = "Gained",
    Lost = "Lost",
  }

  export enum WindowLifecycleKind {
    Ready = "Ready",
    Suspended = "Suspended",
    Resumed = "Resumed",
    CloseRequested = "CloseRequested",
  }

  export interface ClickEvent {}

  export interface ChangeEvent {
    readonly value: string;
  }

  export interface SubmitEvent {
    readonly value: string;
  }

  export interface PointerEvent {
    readonly kind: PointerKind;
    readonly pointerId: number;
    readonly x: number;
    readonly y: number;
    readonly buttons: number;
    readonly pressure: number;
    readonly context: EventContext;
  }

  export interface WheelEvent {
    readonly deltaX: number;
    readonly deltaY: number;
    readonly x: number;
    readonly y: number;
    readonly context: EventContext;
  }

  export interface KeyboardEvent {
    readonly kind: KeyboardKind;
    readonly key: string;
    readonly code: string;
    readonly repeat: boolean;
    readonly context: EventContext;
  }

  export interface TextInputEvent {
    readonly text: string;
    readonly context: EventContext;
  }

  export interface CompositionEvent {
    readonly kind: CompositionKind;
    readonly text: string;
    readonly selectionStart: number;
    readonly selectionEnd: number;
    readonly context: EventContext;
  }

  export interface FocusEvent {
    readonly kind: FocusKind;
    readonly relatedTarget: Common.HandleRef | null;
    readonly context: EventContext;
  }

  export interface WindowLifecycleEvent {
    readonly kind: WindowLifecycleKind;
    readonly surfaceGeneration?: number;
  }

  export type PropertyValue = number;

  export enum FeatureBit {
    MutationTransactions = 2,
    Semantics = 3,
    TextInputClient = 4,
  }

  export enum NodeType {
    Root = 0,
    View = 1,
    Text = 2,
    Image = 3,
    Scroll = 4,
  }

  export enum PropertyId {
    Width = 1,
    Height = 2,
    MinWidth = 3,
    MinHeight = 4,
    Padding = 5,
    Gap = 6,
    FlexDirection = 7,
    AlignItems = 8,
    JustifyContent = 9,
    BackgroundColor = 10,
    BorderRadius = 11,
    Opacity = 12,
    FontSize = 13,
    FontWeight = 14,
    TextColor = 15,
    ScrollOffsetY = 16,
    FlexGrow = 17,
    Disabled = 18,
  }

  export enum EventId {
    Click = 1,
    Change = 2,
    Submit = 3,
    Pointer = 4,
    Wheel = 5,
    Keyboard = 6,
    TextInput = 7,
    Composition = 8,
    Focus = 9,
    WindowLifecycle = 10,
  }

  export interface EventPayloadMap {
    readonly [EventId.Click]: ClickEvent;
    readonly [EventId.Change]: ChangeEvent;
    readonly [EventId.Submit]: SubmitEvent;
    readonly [EventId.Pointer]: PointerEvent;
    readonly [EventId.Wheel]: WheelEvent;
    readonly [EventId.Keyboard]: KeyboardEvent;
    readonly [EventId.TextInput]: TextInputEvent;
    readonly [EventId.Composition]: CompositionEvent;
    readonly [EventId.Focus]: FocusEvent;
    readonly [EventId.WindowLifecycle]: WindowLifecycleEvent;
  }
  export type EventPayload = EventPayloadMap[keyof EventPayloadMap];
  export type EventCallback = (payload: EventPayload) => void;

  export enum CommandId {
    CreateNode = 1,
    CreateText = 2,
    Insert = 3,
    Remove = 4,
    SetText = 5,
    SetProperty = 6,
    AddEventListener = 7,
    RemoveEventListener = 8,
    Commit = 9,
    Run = 10,
    SetImage = 11,
    RegisterInput = 12,
    ClearProperty = 13,
    SetSemantics = 14,
    ResetSession = 15,
    GetTextInputState = 16,
    ReplaceTextInput = 17,
    GetCompositionBounds = 18,
    ClearSemantics = 19,
    RegisterButton = 20,
  }

  export enum ErrorCode {
    InvalidArgument = 16777217,
    InvalidKind = 16777218,
    WrongOwner = 16777219,
    StaleHandle = 16777220,
    InvalidState = 16777221,
    NotFound = 16777222,
    Cancelled = 16777223,
    PlatformFailure = 16777224,
    InternalFailure = 16777225,
  }

  export interface CommandParams {
    readonly [CommandId.CreateNode]: readonly [type: NodeType];
    readonly [CommandId.CreateText]: readonly [text: string];
    readonly [CommandId.Insert]: readonly [
      child: Common.HandleRef,
      parent: Common.HandleRef,
      before: Common.HandleRef | null,
    ];
    readonly [CommandId.Remove]: readonly [node: Common.HandleRef];
    readonly [CommandId.SetText]: readonly [node: Common.HandleRef, text: string];
    readonly [CommandId.SetProperty]: readonly [
      node: Common.HandleRef,
      property: PropertyId,
      value: PropertyValue,
    ];
    readonly [CommandId.AddEventListener]: readonly [
      node: Common.HandleRef,
      event: EventId,
      callback: EventCallback,
    ];
    readonly [CommandId.RemoveEventListener]: readonly [listener: Common.HandleRef];
    readonly [CommandId.Commit]: readonly [];
    readonly [CommandId.Run]: readonly [title: string];
    readonly [CommandId.SetImage]: readonly [node: Common.HandleRef, path: string];
    readonly [CommandId.RegisterInput]: readonly [
      container: Common.HandleRef,
      textNode: Common.HandleRef,
      placeholder: string,
    ];
    readonly [CommandId.ClearProperty]: readonly [node: Common.HandleRef, property: PropertyId];
    readonly [CommandId.SetSemantics]: readonly [node: Common.HandleRef, semantics: Semantics];
    readonly [CommandId.ResetSession]: readonly [];
    readonly [CommandId.GetTextInputState]: readonly [node: Common.HandleRef];
    readonly [CommandId.ReplaceTextInput]: readonly [
      node: Common.HandleRef,
      range: TextRange,
      text: string,
    ];
    readonly [CommandId.GetCompositionBounds]: readonly [node: Common.HandleRef];
    readonly [CommandId.ClearSemantics]: readonly [node: Common.HandleRef];
    readonly [CommandId.RegisterButton]: readonly [node: Common.HandleRef];
  }

  export interface CommandResults {
    readonly [CommandId.CreateNode]: Common.HandleRef;
    readonly [CommandId.CreateText]: Common.HandleRef;
    readonly [CommandId.Insert]: void;
    readonly [CommandId.Remove]: void;
    readonly [CommandId.SetText]: void;
    readonly [CommandId.SetProperty]: void;
    readonly [CommandId.AddEventListener]: Common.HandleRef;
    readonly [CommandId.RemoveEventListener]: void;
    readonly [CommandId.Commit]: CommitReceipt;
    readonly [CommandId.Run]: void;
    readonly [CommandId.SetImage]: void;
    readonly [CommandId.RegisterInput]: void;
    readonly [CommandId.ClearProperty]: void;
    readonly [CommandId.SetSemantics]: void;
    readonly [CommandId.ResetSession]: void;
    readonly [CommandId.GetTextInputState]: TextInputState;
    readonly [CommandId.ReplaceTextInput]: void;
    readonly [CommandId.GetCompositionBounds]: Rect;
    readonly [CommandId.ClearSemantics]: void;
    readonly [CommandId.RegisterButton]: void;
  }
}

export namespace System {
  export enum FeatureBit {
    Tasks = 2,
    Resources = 3,
    Permissions = 4,
  }

  export enum CommandId {
    ClipboardReadText = 1,
    ClipboardWriteText = 2,
    CancelTask = 3,
    CloseResource = 4,
    ResetSession = 5,
    ReadTextFile = 6,
    WriteTextFile = 7,
    AwaitTask = 8,
    OpenFileDialog = 9,
    SaveFileDialog = 10,
  }

  export enum PermissionId {
    ClipboardRead = 1,
    ClipboardWrite = 2,
    FsRead = 3,
    FsWrite = 4,
    DialogOpen = 5,
    DialogSave = 6,
  }

  export enum TaskKind {
    ClipboardReadText = 1,
    ClipboardWriteText = 2,
    ReadTextFile = 3,
    WriteTextFile = 4,
    OpenFileDialog = 5,
    SaveFileDialog = 6,
  }

  export interface TaskResultMap {
    readonly [TaskKind.ClipboardReadText]: string;
    readonly [TaskKind.ClipboardWriteText]: void;
    readonly [TaskKind.ReadTextFile]: string;
    readonly [TaskKind.WriteTextFile]: void;
    readonly [TaskKind.OpenFileDialog]: string;
    readonly [TaskKind.SaveFileDialog]: string;
  }

  export enum ResourceKind {
    Window = 1,
    File = 2,
    FileWatcher = 3,
    Process = 4,
    HttpRequest = 5,
    Socket = 6,
  }

  export enum ErrorCode {
    InvalidArgument = 33554433,
    InvalidKind = 33554434,
    WrongOwner = 33554435,
    StaleHandle = 33554436,
    InvalidState = 33554437,
    NotFound = 33554438,
    PermissionDenied = 33554439,
    Cancelled = 33554440,
    PlatformFailure = 33554441,
    InternalFailure = 33554442,
    InvalidData = 33554443,
  }

  export interface CommandParams {
    readonly [CommandId.ClipboardReadText]: readonly [];
    readonly [CommandId.ClipboardWriteText]: readonly [text: string];
    readonly [CommandId.CancelTask]: readonly [task: Common.HandleRef];
    readonly [CommandId.CloseResource]: readonly [resource: Common.HandleRef];
    readonly [CommandId.ResetSession]: readonly [];
    readonly [CommandId.ReadTextFile]: readonly [path: string];
    readonly [CommandId.WriteTextFile]: readonly [path: string, text: string];
    readonly [CommandId.AwaitTask]: readonly [task: Common.HandleRef];
    readonly [CommandId.OpenFileDialog]: readonly [
      title: string,
      defaultPath: string,
      filtersJson: string,
    ];
    readonly [CommandId.SaveFileDialog]: readonly [
      title: string,
      defaultPath: string,
      filtersJson: string,
    ];
  }

  export interface CommandResults {
    readonly [CommandId.ClipboardReadText]: Common.HandleRef;
    readonly [CommandId.ClipboardWriteText]: Common.HandleRef;
    readonly [CommandId.CancelTask]: void;
    readonly [CommandId.CloseResource]: void;
    readonly [CommandId.ResetSession]: void;
    readonly [CommandId.ReadTextFile]: Common.HandleRef;
    readonly [CommandId.WriteTextFile]: Common.HandleRef;
    readonly [CommandId.AwaitTask]: string;
    readonly [CommandId.OpenFileDialog]: Common.HandleRef;
    readonly [CommandId.SaveFileDialog]: Common.HandleRef;
  }
}
