[package]
name = "nui-layout-taffy"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Taffy Flexbox layout backend for Nexa UI"

[dependencies]
nui-core = { path = "../nui-core" }
taffy = { version = "0.12", default-features = false, features = ["std", "taffy_tree", "flexbox"] }

[lints]
workspace = true
