import { createRoot, runHost } from "@nexa/compiler-svelte/runtime";

// Generated by `pnpm compile:svelte` before Perry compiles this entrypoint.
// @ts-expect-error The ignored build artifact intentionally has no declaration file.
import Counter from "./dist/Counter.host.js";

const target = createRoot();
new Counter({ target });
runHost();
