import assert from "node:assert/strict";
import {
  appendFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import {
  GENERATED_ARTIFACT_PATHS,
  checkProtocolArtifacts,
  generateProtocolArtifacts,
  writeProtocolArtifacts,
} from "./protocol-codegen.mjs";
import { renderTypeScriptProtocol } from "./protocol-codegen/typescript.mjs";
import { common, contracts } from "./protocol-contract.mjs";

const toolsDir = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(toolsDir, "..");
const generatorPath = path.join(toolsDir, "protocol-codegen.mjs");

function readPackageManifest(relativePath) {
  return JSON.parse(readFileSync(path.join(workspaceRoot, relativePath), "utf8"));
}

test("protocol generator renders deterministic Rust, TypeScript, and Perry artifacts", () => {
  const first = generateProtocolArtifacts();
  const second = generateProtocolArtifacts();

  assert.deepEqual(first, second);
  assert.deepEqual(Object.keys(first).sort(), [...GENERATED_ARTIFACT_PATHS].sort());

  const rust = first["protocol/generated/protocol.rs"];
  assert.match(rust, /^\/\/ @generated by tools\/protocol-codegen\.mjs; DO NOT EDIT\./);
  assert.match(rust, /pub const PROTOCOL_VERSION: ProtocolVersion/);
  assert.match(rust, /pub enum NodeType/);
  assert.match(rust, /pub enum PropertyId/);
  assert.match(rust, /Cancelled = 16777223/);
  assert.doesNotMatch(rust, /CANCELLED =/);

  const typescript = first["packages/protocol/src/index.ts"];
  assert.match(typescript, /^\/\/ @generated by tools\/protocol-codegen\.mjs; DO NOT EDIT\./);
  assert.match(typescript, /declare const handleRefBrand: unique symbol/);
  assert.match(typescript, /export type NexaResult<T>/);
  assert.match(typescript, /export namespace Ui/);
  assert.match(typescript, /export const NodeType = \{/);
  assert.match(typescript, /Cancelled = 16777223/);
  assert.doesNotMatch(typescript, /CANCELLED =/);
  assert.match(typescript, /before: Common\.HandleRef \| null/);
  assert.doesNotMatch(typescript, /before\?: Common\.HandleRef/);

  const uiPerry = JSON.parse(first["protocol/generated/nui-host.perry.json"]);
  const systemPerry = JSON.parse(first["protocol/generated/system-host.perry.json"]);
  assert.equal(uiPerry.generatedBy, "tools/protocol-codegen.mjs");
  assert.equal(systemPerry.generatedBy, "tools/protocol-codegen.mjs");
  assert.equal(uiPerry.abiVersion, "0.5");
  assert.equal(systemPerry.abiVersion, "0.5");
  assert.equal(uiPerry.functions.length, 29);
  assert.equal(systemPerry.functions.length, 7);
  assert.equal(uiPerry.functions[13].name, "js_nui_handshake_v1");
  assert.equal(uiPerry.functions[13].returns, "string");
  assert.equal(systemPerry.functions[2].name, "js_nexa_clipboard_read_text_v1");
  assert.equal(systemPerry.functions[2].returns, "string");
});

test("checked-in Perry package manifests match implemented generated functions", () => {
  const generatedUi = JSON.parse(
    generateProtocolArtifacts()["protocol/generated/nui-host.perry.json"],
  );
  const generatedSystem = JSON.parse(
    generateProtocolArtifacts()["protocol/generated/system-host.perry.json"],
  );
  const packages = [
    ["packages/nui-host/package.json", generatedUi],
    ["packages/system-host/package.json", generatedSystem],
  ];

  const implementedV1 = {
    "packages/nui-host/package.json": new Set([
      "js_nui_handshake_v1",
      "js_nui_create_node_v1",
      "js_nui_add_event_listener_v1",
      "js_nui_remove_event_listener_v1",
      "js_nui_clear_property_v1",
    ]),
    "packages/system-host/package.json": new Set(),
  };
  for (const [relativePath, generated] of packages) {
    const configured = readPackageManifest(relativePath).perry.nativeLibrary.functions;
    const generatedConfigured = generated.functions.filter(
      (entry) => !entry.name.endsWith("_v1") || implementedV1[relativePath].has(entry.name),
    );
    assert.deepEqual(configured, generatedConfigured, relativePath);
  }
});

test("TypeScript renderer rejects semantic u64 instead of mapping it to number", () => {
  const manifests = {
    common: structuredClone(common.manifest),
    ui: structuredClone(contracts.ui.manifest),
    system: structuredClone(contracts.system.manifest),
  };
  manifests.ui.commands[0].params[0].type = "u64";

  assert.throws(() => renderTypeScriptProtocol(manifests), /must not render semantic u64/);
});

test("TypeScript renderer uses explicit null for optional HandleRef fields", () => {
  const manifests = {
    common: structuredClone(common.manifest),
    ui: structuredClone(contracts.ui.manifest),
    system: structuredClone(contracts.system.manifest),
  };
  manifests.ui.types.push({
    name: "OptionalHandleFixture",
    kind: "record",
    fields: [
      {
        name: "anchor",
        type: "common.HandleRef",
        handleKind: "common.Node",
        optional: true,
      },
    ],
  });

  const typescript = renderTypeScriptProtocol(manifests);
  assert.match(typescript, /readonly anchor: Common\.HandleRef \| null/);
  assert.doesNotMatch(typescript, /readonly anchor\?: Common\.HandleRef/);
});

test("protocol generator writes once, then detects missing, changed, and unexpected artifacts", () => {
  const temporaryRoot = mkdtempSync(path.join(tmpdir(), "nexa-ui-protocol-codegen-"));
  try {
    assert.deepEqual(writeProtocolArtifacts({ root: temporaryRoot }), GENERATED_ARTIFACT_PATHS);
    assert.deepEqual(writeProtocolArtifacts({ root: temporaryRoot }), []);
    assert.doesNotThrow(() => checkProtocolArtifacts({ root: temporaryRoot }));

    const rustPath = path.join(temporaryRoot, "protocol/generated/protocol.rs");
    appendFileSync(rustPath, "// manual edit\n");
    assert.throws(
      () => checkProtocolArtifacts({ root: temporaryRoot }),
      /out of date: protocol\/generated\/protocol\.rs/,
    );

    writeProtocolArtifacts({ root: temporaryRoot });
    rmSync(rustPath);
    assert.throws(
      () => checkProtocolArtifacts({ root: temporaryRoot }),
      /missing: protocol\/generated\/protocol\.rs/,
    );

    writeProtocolArtifacts({ root: temporaryRoot });
    const unexpectedPath = path.join(temporaryRoot, "protocol/generated/stale.txt");
    mkdirSync(path.dirname(unexpectedPath), { recursive: true });
    writeFileSync(unexpectedPath, "stale\n");
    assert.throws(
      () => checkProtocolArtifacts({ root: temporaryRoot }),
      /unexpected: protocol\/generated\/stale\.txt/,
    );
  } finally {
    rmSync(temporaryRoot, { recursive: true, force: true });
  }
});

test("checked-in protocol artifacts are exact generator snapshots", () => {
  const artifacts = generateProtocolArtifacts();
  for (const [relativePath, expected] of Object.entries(artifacts)) {
    assert.equal(readFileSync(path.join(workspaceRoot, relativePath), "utf8"), expected);
  }
  assert.doesNotThrow(() => checkProtocolArtifacts({ root: workspaceRoot }));
});

test("generated Rust and TypeScript declarations compile", () => {
  const temporaryRoot = mkdtempSync(path.join(tmpdir(), "nexa-ui-protocol-compile-"));
  try {
    const rust = spawnSync(
      "rustc",
      [
        "--edition",
        "2021",
        "--crate-name",
        "nexa_protocol_generated",
        "--crate-type",
        "lib",
        "protocol/generated/protocol.rs",
        "--out-dir",
        temporaryRoot,
      ],
      { cwd: workspaceRoot, encoding: "utf8" },
    );
    assert.equal(rust.status, 0, rust.stderr || rust.stdout);

    const pnpm = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
    const typescript = spawnSync(
      pnpm,
      [
        "exec",
        "tsc",
        "--noEmit",
        "--target",
        "ES2022",
        "--module",
        "NodeNext",
        "--moduleResolution",
        "NodeNext",
        "--strict",
        "--skipLibCheck",
        "packages/protocol/src/index.ts",
      ],
      { cwd: workspaceRoot, encoding: "utf8" },
    );
    assert.equal(typescript.status, 0, typescript.stderr || typescript.stdout);
  } finally {
    rmSync(temporaryRoot, { recursive: true, force: true });
  }
});

test("protocol codegen CLI exposes a clean --check drift gate", () => {
  const result = spawnSync(process.execPath, [generatorPath, "--check"], {
    cwd: workspaceRoot,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /Protocol artifacts are up to date\./);
});
