name: TypeScript

on:
  workflow_call:
  workflow_dispatch:

jobs:
  typecheck:
    name: typecheck & format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6.0.9
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format:check

      - name: Typecheck
        run: pnpm typecheck
